### PR TITLE
Add background

### PR DESCRIPTION
**Pull request by LeandroStanger**
The Background is used in the App Center of Endless OS
An example image
Captura de tela de 2019-05-11 20-02-07

### CODE REVIEW

**Comment by TingPing** [comment]
License?

**Comment by LeandroStanger** [comment]
Pixabay License
Free for commercial use
No attribution required
pixabay.com/photos/white-board-startup-start-up-593300

**Comment by TingPing** [comment]
@JBBgameich For what its worth Flathub is not recommending applications add background images. They are specific to EndlessOS and never pushed to be used elsewhere. The images are also low quality (its not even the right aspect ratio...) and not clearly licensed (its from a user uploaded content website).

**Comment by JBBgameich** [comment]
Should I revert the change? I'm not yet really experienced with the flathub policies, so for changes not concerning the flatpak recipe itself I usually just merge PRs that don't cause any visible issues.

**Comment by TingPing** [comment]
You don't have to but its effectively dead weight for you to maintain.

**Pull request merged**
